services:
    db:
      image: postgres:latest
      hostname: db
      environment:
        - POSTGRES_PASSWORD=myawesomepass
        - POSTGRES_USER=u_develop
        - POSTGRES_DB=develop_db
      ports:
        - "5432:5432"
      deploy:
        resources:
          limits:
            cpus: "0.25"
            memory: "210MB"
